# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: faceid_ai.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x66\x61\x63\x65id_ai.proto\x12\x03rpc\"5\n\x0c\x45mployeeInfo\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x19\n\x05image\x18\x02 \x01(\x0b\x32\n.rpc.Image\" \n\x0e\x45mployeeStatus\x12\x0e\n\x06status\x18\x01 \x01(\x08\"\x1e\n\x05Image\x12\x15\n\rencoded_image\x18\x01 \x01(\x0c\"\xd9\x01\n\rFaceEmbedding\x12*\n\x0e\x66\x65\x61ture_vector\x18\x01 \x01(\x0b\x32\x12.rpc.FeatureVector\x12.\n\x0cvector_state\x18\x02 \x01(\x0e\x32\x18.rpc.FaceEmbedding.State\"l\n\x05State\x12\x15\n\x11STATE_UNSPECIFIED\x10\x00\x12\x11\n\rSTATE_SUCCESS\x10\x01\x12\x13\n\x0fSTATE_NOT_FOUND\x10\x02\x12\x13\n\x0fSTATE_MULTIFACE\x10\x03\x12\x0f\n\x0bSTATE_ERROR\x10\x04\"\x1f\n\rFeatureVector\x12\x0e\n\x06vector\x18\x01 \x03(\x02\x32z\n\x08\x46\x61\x63\x65IdAi\x12\x34\n\x10GetFeatureVector\x12\n.rpc.Image\x1a\x12.rpc.FaceEmbedding\"\x00\x12\x38\n\x0c\x42\x65\x41tYourDesk\x12\x11.rpc.EmployeeInfo\x1a\x13.rpc.EmployeeStatus\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'faceid_ai_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPLOYEEINFO._serialized_start=24
  _EMPLOYEEINFO._serialized_end=77
  _EMPLOYEESTATUS._serialized_start=79
  _EMPLOYEESTATUS._serialized_end=111
  _IMAGE._serialized_start=113
  _IMAGE._serialized_end=143
  _FACEEMBEDDING._serialized_start=146
  _FACEEMBEDDING._serialized_end=363
  _FACEEMBEDDING_STATE._serialized_start=255
  _FACEEMBEDDING_STATE._serialized_end=363
  _FEATUREVECTOR._serialized_start=365
  _FEATUREVECTOR._serialized_end=396
  _FACEIDAI._serialized_start=398
  _FACEIDAI._serialized_end=520
# @@protoc_insertion_point(module_scope)
